version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "createPodcast"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-l4fwhknqjwyh"
s3_prefix = "createPodcast"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
